### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by WarrenGraham** [ola-zbieranska/easy-free-dashboard-app#2]
HI, I found your project through Linikedin priofile. It's look cool, but if I can sugesst you improvement, there is missing quick example of your framework in action, showed via screenshots or commands. ;)

**Comment by ola-zbieranska** [comment]
Hi, Good point! Thanks for the message, I added some screenshots from the application. I have a problem with correctly downloading data for visualization. I will post visualization screanshots after code corrections :)
